import FormConfig from './form-props/form-config'

export default {
  config: FormConfig.defaultValue(),
  'elements': [
    {
      'key': 'user',
      'display': 'inline-block',
      'width': '50%',
      'labelWidth': '90px',
      'labelShown': 1,
      'shown': 1,
      'size': 'mini',
      // 'marginRight': '0px',
      'placeholder': '请输入',
      'labelAlign': 'right',
      'controlBorderColor': '#DCDFE6',
      'controlBorderWidth': '1px',
      'controlBorderStyle': 'solid',
      'controlBorderRadius': '0px',
      'type': 'fd-input-dialog',
      'name': '请假人',
      'readonly': 0,
      'required': 0,
      'multiple': 0,
      'id': 'Ti6A51x9ea2TXhEfhPGQQQqAc44GCahs',
      'controlBgColor': 'rgba(245, 245, 245, 1)',
      'paddingRight': '8px',
      'marginTop': '-1px',
      'marginRight': '-1px'
    },
    {
      'key': 'dept',
      'display': 'inline-block',
      'width': '50%',
      'labelWidth': '90px',
      'labelShown': 1,
      'shown': 1,
      'size': 'mini',
      'marginRight': '0px',
      'placeholder': '请输入',
      'labelAlign': 'right',
      'controlBorderColor': '#DCDFE6',
      'controlBorderWidth': '1px',
      'controlBorderStyle': 'solid',
      'controlBorderRadius': '0px',
      'type': 'fd-input-dialog',
      'name': '所属部门',
      'readonly': 0,
      'required': 0,
      'multiple': 0,
      'id': 'kik4rkdmA3STAHDdioUD1xke8XjGJNDN',
      'controlBgColor': 'rgba(245, 245, 245, 1)',
      'paddingRight': '8px',
      'marginLeft': '0px',
      'marginTop': '-1px'
    },
    {
      'key': 'daterange',
      'display': 'block',
      'width': '100%',
      'labelWidth': '90px',
      'labelShown': 1,
      'shown': 1,
      'size': 'mini',
      'marginRight': '0px',
      'placeholder': '请输入',
      'labelAlign': 'right',
      'controlBorderColor': '#DCDFE6',
      'controlBorderWidth': '1px',
      'controlBorderStyle': 'solid',
      'controlBorderRadius': '0px',
      'type': 'fd-date',
      'name': '请假时间',
      'readonly': 0,
      'autofill': 0,
      'required': 0,
      'format': 'yyyy-MM-dd',
      'dateType': 'daterange',
      'id': 'X1SbzE2aIYw3REkOa2C6DSeocfXLtUTH',
      'controlBgColor': 'rgba(245, 245, 245, 1)',
      'marginTop': '-1px',
      'paddingRight': '8px'
    },
    {
      'key': 'reason',
      'display': 'block',
      'width': '100%',
      'labelWidth': '90px',
      'labelShown': 1,
      'shown': 1,
      'size': 'mini',
      'marginRight': '0px',
      'placeholder': '请输入',
      'labelAlign': 'right',
      'controlBorderColor': '#DCDFE6',
      'controlBorderWidth': '1px',
      'controlBorderStyle': 'solid',
      'controlBorderRadius': '0px',
      'type': 'fd-textarea',
      'name': '请假原因',
      'readonly': 0,
      'autofill': 0,
      'required': 0,
      'digit': 0,
      'id': 'gwYNaCgqKZeQucEseH8bQwbp7S5K07a3',
      'autosize': 0,
      'controlBgColor': 'rgba(245, 245, 245, 1)',
      'marginTop': '-1px',
      'paddingRight': '8px'
    },
    {
      'key': 'attach',
      'display': 'block',
      'width': '100%',
      'labelWidth': '90px',
      'labelShown': 1,
      'shown': 1,
      'size': 'mini',
      'marginRight': '0px',
      'placeholder': '请输入',
      'labelAlign': 'right',
      'controlBorderColor': '#DCDFE6',
      'controlBorderWidth': '1px',
      'controlBorderStyle': 'solid',
      'controlBorderRadius': '0px',
      'type': 'fd-attach',
      'name': '请假证明',
      'readonly': 0,
      'required': 0,
      'attachLimit': 9,
      'attachImage': 0,
      'attachImageDisplay': 'text',
      'attachImageWidth': 96,
      'attachImageHeight': 96,
      'id': 'oz1V7MRbGILGYls9o9MW2KBSYQS0Xw9P',
      'attachMultiple': 0,
      'controlBgColor': 'rgba(245, 245, 245, 1)',
      'paddingRight': '8px',
      'marginTop': '-1px'
    }
  ]
}
